service_name: "itdefence"
stack_type: "capacitor"
target_cluster: "prod"
deploy:
  dir: "/opt/itdefence"
  web_port: 7979
features:
  - typecheck
  - tests
  - e2e

custom_stages:
  - name: "Security Scan"
    insert_before: "Test"
    steps: |
      script {
          echo "Running custom security scan..."
          // sh 'npm run scan'
      }
